# ==============================================================
# CONFIGURATION
# ==============================================================
# Jekyll configuration files are written in YAML format.
# Colons, tabs/spacing, and quotes are meaningful in YAML.
# It is recommended you look at the following guide to avoid
# syntax errors in this file:
# ~> https://learnxinyminutes.com/docs/yaml/
#
#
# Questions ?
# ~> https://minicomp.github.io/wiki/#/
# ~> https://gitter.im/minicomp/wax/
#
# ---------------------------------------------------------------
# MAIN SETTINGS
# ---------------------------------------------------------------
# Feel free to change these! For more info, refer to:
# ~> https://jekyllrb.com/docs/configuration/options/

title:            'Examples Repository'
description:      'Minimalist Examples Repository with Jekyll'
url:              'https://visualizingthefuture.github.io'
baseurl:          '/examples-repository'
copyright:        'Example copyright org, 2020'
logo:             '/assets/logo.png'
integration_spreadsheet_key: 1jLCQG-Z5gwpT7zgF0MT6ww3A-QBf1ktcZuTQhfyjxd0
github_user: visualizingthefuture
github_repo: examples-repository
gdrive:
  sheet: "google-sheet-to-github-website-links"

# ---------------------------------------------------------------
# BUILD SETTINGS
# ---------------------------------------------------------------
# Best not to mess with these unless you know what you're doing!

permalink: 'pretty'
sass:
  style: compressed
exclude:
  - Gemfile*
  - Rakefile
  - vendor
  - spec
  - README.md
webrick:
  headers:
    'Access-Control-Allow-Origin': '*'
kramdown:
 auto_ids:       true
 footnote_nr:    1
 entity_output:  as_char
 footnote_backlink: "&#x21a9;&#xfe0e;"
 toc_levels:     1..6
 smart_quotes:   lsquo,rsquo,ldquo,rdquo
 enable_coderay: false
#theme: jekyll-theme-cayman


# --------------------------------------------------------------
# COLLECTION SETTINGS
# --------------------------------------------------------------
# Wax leverages Jekyll collections for much of its
# functionality, therefor some of the keys below are from
# Jekyll while others are Wax-specific.
# For more info, refer to:
# ~> https://jekyllrb.com/docs/collections/

collections:
  exhibits:
    output: true
  datavis: # name of collection
    output: true # makes sure pages are output as html files
    layout: 'labels' # the layout for the pages to use
    metadata:
      source: 'datavis.csv' # path to the metadata file within `_data`
    images:
      source: 'raw_images/datavis' # path to the directory of images within `_data`

# --------------------------------------------------------------
# SEARCH INDEX SETTINGS
# --------------------------------------------------------------
# You can create multiple search indexes below (though only one is
# recommended!) by specifying
# an `index` file to write it to and some `collections` for it to index
# and running `$ bundle exec rake wax:search` .

search:
  main:
    index: '/search/index.json' # file the index will get written to
    collections:
      datavis:
        content: false # whether or not to index page content
        fields: # the metadata fields to index
          - title
          - description
          - author
          - year
          - object_type
          - topic
          - purpose
          - source
          - audience_level
          - audience_composition
          - additional_properties
          - pid
          - order
          - layout
          - collection

# --------------------------------------------------------------
# SITE MENU SETTINGS
# --------------------------------------------------------------
# Each menu item needs a `label` (whats shown), and a `link`
# (where it goes). An item can optionally have a dropdown
# submenu via `sub`.

menu:
  - label: 'Featured'
    sub:
      - label: 'Featured Article A'
        link: '/featured/a/'
      - label: 'Featured Article B'
        link: '/featured/b/'
  - label: 'Browse'
    sub:
      - label: 'Data Visualizations'
        link: '/datavis/'
      - label: 'Data Sets'
        link: '/datavis/'
  - label: 'Search'
    link: '/search/'

# --------------------------------------------------------------
# SITE FOOTER SETTINGS
 # - label: 'Browse'
 #   sub:
 #     - label: 'Browse Data Visualizations'
 #       link: '/collection/datavis/'
 #     - label: 'Browse Data Sets'
 #       link: ''/collection/dataset/'
# --------------------------------------------------------------
#

footer:
  links:
    - label: 'GitHub'
      link: 'https://github.com/amawest/wax-1'
    - label: 'Credits'
      link: '/credits'
    - label: 'Website'
      link: 'https://visualizingthefuture.github.io//'
  logos:
    - img: '/img/logo.png'

# FIN
